apiVersion: v1
kind: Service
metadata:
  name: studentlist
  labels:
    app: studentlist
  namespace: studentlist
spec:
  type: NodePort
  selector:
    app: studentlist
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008