apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: studentlist
  namespace: studentlist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: studentlist
      tier: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: studentlist
        tier: api
    spec:
      containers:
      - name: api
        image: rodriguez003/api-image:1.0
        ports:
        - containerPort: 5000
          name: api
        volumeMounts:
        - name:  api-persistent-storage
          mountPath: /data
      volumes:
      - name:  api-persistent-storage
        hostPath:  
          path: /home/vagrant/kubernetes-Labs/mini-projet2/student-list/simple_api
          type: Directory
          
